# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x12\x03\x61\x64s\"6\n\x0cQueryRequest\x12\x14\n\x0crequest_json\x18\x01 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\"#\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"$\n\x06Schema\x12\x1a\n\x06\x66ields\x18\x01 \x03(\x0b\x32\n.ads.Field\"?\n\x04\x43\x65ll\x12\x0b\n\x01\x64\x18\x01 \x01(\x01H\x00\x12\x0b\n\x01i\x18\x02 \x01(\x12H\x00\x12\x0b\n\x01s\x18\x03 \x01(\tH\x00\x12\x0b\n\x01\x62\x18\x04 \x01(\x08H\x00\x42\x03\n\x01v\"\x1f\n\x03Row\x12\x18\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\t.ads.Cell\"\"\n\x08RowBatch\x12\x16\n\x04rows\x18\x01 \x03(\x0b\x32\x08.ads.Row\"S\n\x06\x43olumn\x12\x13\n\x07\x64oubles\x18\x01 \x03(\x01\x42\x02\x10\x01\x12\x10\n\x04ints\x18\x02 \x03(\x12\x42\x02\x10\x01\x12\x0f\n\x07strings\x18\x03 \x03(\t\x12\x11\n\x05\x62ools\x18\x04 \x03(\x08\x42\x02\x10\x01\"?\n\rColumnarBatch\x12\x1c\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x0b.ads.Column\x12\x10\n\x08num_rows\x18\x02 \x01(\x05\"\x83\x01\n\nQueryReply\x12\x1d\n\x06schema\x18\x01 \x01(\x0b\x32\x0b.ads.SchemaH\x00\x12\"\n\trow_batch\x18\x02 \x01(\x0b\x32\r.ads.RowBatchH\x00\x12\'\n\tcol_batch\x18\x03 \x01(\x0b\x32\x12.ads.ColumnarBatchH\x00\x42\t\n\x07payload2<\n\x0b\x44\x61taService\x12-\n\x05Query\x12\x11.ads.QueryRequest\x1a\x0f.ads.QueryReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLUMN'].fields_by_name['doubles']._loaded_options = None
  _globals['_COLUMN'].fields_by_name['doubles']._serialized_options = b'\020\001'
  _globals['_COLUMN'].fields_by_name['ints']._loaded_options = None
  _globals['_COLUMN'].fields_by_name['ints']._serialized_options = b'\020\001'
  _globals['_COLUMN'].fields_by_name['bools']._loaded_options = None
  _globals['_COLUMN'].fields_by_name['bools']._serialized_options = b'\020\001'
  _globals['_QUERYREQUEST']._serialized_start=27
  _globals['_QUERYREQUEST']._serialized_end=81
  _globals['_FIELD']._serialized_start=83
  _globals['_FIELD']._serialized_end=118
  _globals['_SCHEMA']._serialized_start=120
  _globals['_SCHEMA']._serialized_end=156
  _globals['_CELL']._serialized_start=158
  _globals['_CELL']._serialized_end=221
  _globals['_ROW']._serialized_start=223
  _globals['_ROW']._serialized_end=254
  _globals['_ROWBATCH']._serialized_start=256
  _globals['_ROWBATCH']._serialized_end=290
  _globals['_COLUMN']._serialized_start=292
  _globals['_COLUMN']._serialized_end=375
  _globals['_COLUMNARBATCH']._serialized_start=377
  _globals['_COLUMNARBATCH']._serialized_end=440
  _globals['_QUERYREPLY']._serialized_start=443
  _globals['_QUERYREPLY']._serialized_end=574
  _globals['_DATASERVICE']._serialized_start=576
  _globals['_DATASERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
